trigger:
  branches:
    include:
    - 'main'
    - 'preview'
    - 'dev'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |    
    docker version
    docker buildx version
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    docker buildx create --name container-builder --driver docker-container --driver-opt default-load=true --bootstrap --use
  displayName: 'Setup qemu and docker buildx'

- script: |
    docker buildx build -f Dockerfile --platform="linux/amd64" --output="type=image" -t weihanli/dotnet-httpie:latest -t weihanli/dotnet-httpie:preview -t weihanli/dotnet-httpie:stable .
    docker buildx build -f Dockerfile --platform="linux/arm64" --output="type=image" -t weihanli/dotnet-httpie:latest -t weihanli/dotnet-httpie:preview -t weihanli/dotnet-httpie:stable .
  displayName: 'Docker build Script'
